//! Raw FFI bindings to ParKissat-RS
//!
//! This module contains the low-level C interface bindings generated by bindgen.
//! Use the safe wrapper in the parent module instead of calling these directly.

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]

// Include the generated bindings
include!(concat!(env!("OUT_DIR"), "/bindings.rs"));

// Re-export the result constants for easier access
pub const PARKISSAT_SAT: ParkissatResult = 10;
pub const PARKISSAT_UNSAT: ParkissatResult = 20;
pub const PARKISSAT_UNKNOWN: ParkissatResult = 0;